# Generated by Django 4.1a1 on 2022-07-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('img_url', models.ImageField(upload_to='')),
                ('discount', models.FloatField(default=0)),
            ],
        ),
    ]
