# Generated by Django 4.1a1 on 2022-08-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
