# Generated by Django 4.1a1 on 2022-09-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
