# Generated by Django 4.1a1 on 2022-09-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default-profile-pic.jpeg', upload_to='profile_images'),
        ),
    ]
